#!/bin/sh
#
# This shell script is a simpler wrapper for the Expyriment command line
# interface.
# 
# See COPYING file distributed along with the python-expyriment package for 
# the copyright and license terms.

set -e
case $1 in
	-h|--help) python -m expyriment.cli -h | sed 's/ python -m expyriment.cli / expyriment-cli /g';;
	*) python -m expyriment.cli $*;;
esac
