[project]
authors = [
  {name = "Florian Krause", email = "florian@expyriment.org"},
  {name = "Oliver Lindemann", email = "oliver@expyriment.org"},
]
description = 'A Python library for cognitive and neuroscientific experiments'
license = {file = "COPYING.txt"}
name = "expyriment"
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["version"]
keywords = ["experiment control", "open science",
            "neuroscience", "experimental psychology"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

dependencies = [
  "pygame>=2.5.2,<3",
  "pyopengl>=3,<4",
]

[project.optional-dependencies]
all = [
  "numpy>=1.6,<3",
  "pyserial>=3,<4",
  "pyparallel>=0.2,<1",
  "mediadecoder>=0.2.2,<1",
]
data_preprocessing = ["numpy>=1.6,<3"]
parallelport_linux = ["pyparallel>=0.2,<1"]
serialport = ["pyserial>=3,<4"]
video = ["mediadecoder>=0.2.2,<1"]

[project.urls]
"Bug Tracker" = "https://github.com/expyriment/expyriment/issues"
"Documentation" = "http://docs.expyriment.org"
"Homepage" = 'http://www.expyriment.org'

[project.scripts]
expyriment="expyriment.cli:main"

[tool.setuptools.package-data]
"expyriment" = ["*.png", "_fonts/*.*"]
