on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # TODO: Test if this doesn't trigger with dev releases as well!
jobs:
  build-and-deploy-dev:
    name: Build and deploy a development release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/expyriment  # TODO: Change to PyPi after testing!
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install flit
      - name: Build
        run: |
          make build
      - name: Get release info
        run: | 
          echo "version=${GITHUB_REF_NAME:1}" >> $GITHUB_OUTPUT
          echo "name=Expyriment ${GITHUB_REF_NAME:1}" >> $GITHUB_OUTPUT
        id: release_info
      - name: Create release message  # TODO: Have same formatting as current release messages!
        run: |
          echo "**For installation instructions, please see https://docs.expyriment.org/Installation.html!**\n\n" > release_message.md
          awk '/Version ${{ steps.release_info.outputs.version }}/{flag=1;print;next}/Version/{flag=0}flag' CHANGES.md >> release_message.md
      - name: Make GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.release_info.outputs.name }}
          bodyFile: "release_message.md"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      
