on:
  push:
    tags:
      - 'v[0-9]+(\.[0-9]+)?(\.[0-9]+)?\.dev[0-9]+'
jobs:
  build-and-deploy-dev:
    name: Build and deploy a development release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/expyriment
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install flit
      - name: Build
        run: |
          flit build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
